# STAGES OF OUR BUILD
stages:
  - build
  - test
  - deploy

# Pre-Merge Environment #1 check build and delpoy Docker image using Cloud Build
cu-website:pre_dev_deploy:
  image: google/cloud-sdk:alpine
  stage: deploy
  environment: cu-app-dev1
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
  before_script:
    - bash tools/gcloud_dev_acc.sh
  # when: manual
  script:
    - bash tools/pre_dev_deploy.sh

# Pre-Merge Environment #2 check build and deploy Docker image using Cloud Build
cu-website:pre_dev_deploy2:
  image: google/cloud-sdk:alpine
  stage: deploy
  environment: cu-app-dev2
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
  before_script:
    - bash tools/gcloud_dev_acc.sh
  when: manual
  script:
    - bash tools/pre_dev_deploy2.sh


# Build docker image using Cloud Build
cu-website:build:
  image: google/cloud-sdk:alpine
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives" 
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_MERGE_REQUEST_APPROVED == "true" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      changes:
        - composerup/*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives" 
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_MERGE_REQUEST_APPROVED == "true" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      changes:
        - docs/composerup/*
  before_script:
    - bash tools/gcloud_dev_acc.sh
 # when: manual
  script:
    - cd composerup
    - tar -czf composerup-dev.tgz *
    - gcloud builds submit composerup-dev.tgz
      --tag us-central1-docker.pkg.dev/composer-up-dev/composerup-dev/composerup-dev:$CI_COMMIT_REF_SLUG
  retry: 2

# Deploy the container image to Cloud Run
cu_website:dev_deploy:
  environment: cu-website-dev
  image: google/cloud-sdk:alpine
  stage: deploy
  rules:
   # - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives" 
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_MERGE_REQUEST_APPROVED == "true" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      changes:
        - composerup/*
   # - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_REF_NAME == "development"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives" 
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
    - if: $CI_MERGE_REQUEST_APPROVED == "true" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      changes:
        - docs/composerup/*
  needs: ["cu-website:build"]
  before_script:
    - bash tools/gcloud_dev_acc.sh
  script:
    - gcloud run deploy composerup-dev
      --image us-central1-docker.pkg.dev/composerup-dev/composerup-dev/composerup-dev:$CI_COMMIT_REF_SLUG
      --region us-central1
      --service-account cu-dev-cloud-cd@composerup-dev.iam.gserviceaccount.com
  retry: 2